# Generated by Django 5.1.2 on 2024-10-14 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-modified_at',), 'verbose_name_plural': 'Беседы'},
        ),
        migrations.AlterModelOptions(
            name='conversationmessage',
            options={'verbose_name_plural': 'Сообщения'},
        ),
    ]
